name: CI tests on push

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup poetry
        run: |
          sudo -H pip install -U poetry
      - name: Install packages
        run: |
          make install
      - name: Run linter
        run: |
          poetry run prospector ./py_ocpi --profile .prospector.yaml
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup poetry
        run: |
          sudo -H pip install -U poetry
      - name: Install packages
        run: |
          make install
      - name: Run test suite
        run: |
          poetry run pytest -v
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup poetry
        run: |
          sudo -H pip install -U poetry
      - name: Install packages
        run: |
          make install
      - name: Run bandit
        run: |
          poetry run bandit -r ./py_ocpi
